//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facebook.Recources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Facebook.Recources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Already Like This Post.
        /// </summary>
        public static string AlreadyLike {
            get {
                return ResourceManager.GetString("AlreadyLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not Exsist.
        /// </summary>
        public static string EmailNotExsist {
            get {
                return ResourceManager.GetString("EmailNotExsist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Email Is already exsist.
        /// </summary>
        public static string EmailNotUnique {
            get {
                return ResourceManager.GetString("EmailNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address is not Valid.
        /// </summary>
        public static string EmailNotValid {
            get {
                return ResourceManager.GetString("EmailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Birth date can not be empty.
        /// </summary>
        public static string EmptyBirthDate {
            get {
                return ResourceManager.GetString("EmptyBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment Content can not be Empty.
        /// </summary>
        public static string EmptyComment {
            get {
                return ResourceManager.GetString("EmptyComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User First name can not be empty.
        /// </summary>
        public static string EmptyFirstName {
            get {
                return ResourceManager.GetString("EmptyFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Gender can not be empty.
        /// </summary>
        public static string EmptyGender {
            get {
                return ResourceManager.GetString("EmptyGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Last name can not be empty.
        /// </summary>
        public static string EmptyLastName {
            get {
                return ResourceManager.GetString("EmptyLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Phone Number can not be empty.
        /// </summary>
        public static string EmptyNumber {
            get {
                return ResourceManager.GetString("EmptyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Password can not be empty.
        /// </summary>
        public static string EmptyPassword {
            get {
                return ResourceManager.GetString("EmptyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post text can not be Empty.
        /// </summary>
        public static string EmptyPostText {
            get {
                return ResourceManager.GetString("EmptyPostText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Data can not be empty.
        /// </summary>
        public static string EmptyUser {
            get {
                return ResourceManager.GetString("EmptyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Gender Id does not Exsist.
        /// </summary>
        public static string GenderNotExsist {
            get {
                return ResourceManager.GetString("GenderNotExsist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or Password is not Correct.
        /// </summary>
        public static string IncorrectEmailOrPassword {
            get {
                return ResourceManager.GetString("IncorrectEmailOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password is Incorrect.
        /// </summary>
        public static string IncorrectPassword {
            get {
                return ResourceManager.GetString("IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Exceed 255 character.
        /// </summary>
        public static string LongString {
            get {
                return ResourceManager.GetString("LongString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not update Record without Id.
        /// </summary>
        public static string MissingId {
            get {
                return ResourceManager.GetString("MissingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Account is not active yet.
        /// </summary>
        public static string NotActive {
            get {
                return ResourceManager.GetString("NotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number is not Valid.
        /// </summary>
        public static string NotValidPhoneNumber {
            get {
                return ResourceManager.GetString("NotValidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Role Id does not Exsist.
        /// </summary>
        public static string RoleNotExsist {
            get {
                return ResourceManager.GetString("RoleNotExsist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password can&apos;t be less than 5 character.
        /// </summary>
        public static string ShortPassword {
            get {
                return ResourceManager.GetString("ShortPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code you Entered is not Correct.
        /// </summary>
        public static string WrongCode {
            get {
                return ResourceManager.GetString("WrongCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Extention must be jpg or png.
        /// </summary>
        public static string WrongFormat {
            get {
                return ResourceManager.GetString("WrongFormat", resourceCulture);
            }
        }
    }
}
